var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                      o                         ",
   "                      xx       xx       x           xx                          ",
   "               x       xx ooo xx        x     xx                                ",
   "               x        xx   xx     xxxxxo                                      ",
   "               x         xxoxx                                                  ",
   "               x    p     xxx                                              o x  ",
   "  x            x    x      x             xxxxxxxxxxxxxxxxxxxxxxxx          o x  ",
   "  x            x   xxx  o                      oo                          o x  ",
   "  x               xx x                                          xxxx       o x  ",
   "  x          x   xxooo  o            xxxxx           ooooo                   x  ",
   "  x  @     z x   x                   x                            xxxxx      x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxx  xxxxxx      x         xxxxxxxxx  ",
   "                              x   x           oooo         x                    ",
   "                              x!!!x       oooo        !!!!!x                    ",
   "                              x!!!x   ooooo          p!!!!!x                    ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      xv x                        xxxxxxx  x!x  ",
   "                                      x!!x                     xxxx     xxxx!x  ",
   "                                      x!!xxxxxxx              xx           x!x  ",
   "                                      xxooooooooooxx         xx            x!x  ",
   "                                       xxxxxxxxxx!!x         x  o   o   o  x!x  ",
   "                                                xx!x                      xx!x  ",
   "                                                 x!x        xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx          !!!!!!!!!!!!!!xx  ",
   "                                                        xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx   ",
   "                             xxxxoooooxxxx                                      ",
   "             x vvv x            xxxxxxx        xxx                              ",
   "             x     x                        x x        x                        ",
   "             x     x                          x         x                       ",
   "             x     x                           xx        x                      ",
   "                                                x         x                     ",
   "             x   z o      o  @      x   x        x         x                    ",
   "               xxxxxxx    xxxxxxx   x   x         x         x                   ",
   "                     xx  xxxxxxx    x   x   xxxxxxxxx       x                   ",
   "             x        xx        x o x       xxxx   x   x   x                    ",
   "                       x        x   x        x xx   x   x  x                    ",
   "    xxx                x   x    x xx   xxxxx   xxxxxx      x                    ",
   "    xxxx o x x     x               x     o     x x         x                    ",
   "                       x!!!!!!xx     xx!!!!!!!!x x         x                    ",
   "!!!!x x!!!!!!x               xx    xxxxxxxxxxxxx xx  o o  xx                    ",
   "                       x!!!!!x                    xx     xx                     ",
   "!!!!x x!!!!!!x                                     xxxxxxx                      ",
   "                       x!!!!!xx                                                 ",
   "xxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                 ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                               x x                              ",
   "  x                   v       v x    xxx    xxxxxxx                       xxxxxx",
   "  x                    v     v  x           x                              xxx  ",
   "  x                     v   v   xx          x          @                   x o x",
   "  x                      vv    x        xxxxx       |xxxx|    |xxxx|     xxx   x",
   "  x                                o o    x                                     ",
   "  x                                       x                                     ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                "],
  ["                                                                                ",
   "       xx           xx    xx    xxxxx        xxxxxxxxx                          ",
   "         xx       xx      xx  x      xx      xx       xx                        ",
   "           xx   xx        xx x       xx       xx      xxx                       ",
   "             x x          xx         xx        xx                               ",
   "              x           xxxxxxxxxxxxx    x     xx                             ",
   "              x           xx         xx     xx     xx                           ",
   "              x           xx         xx      xxxxxxxxx                          ",
   "                                                                                ",
   "                                                                                "],
 ];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
